# Generated by Django 6.0.4 on 2026-05-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.FloatField()),
                ('math_marks', models.FloatField()),
                ('english_marks', models.FloatField()),
                ('science_marks', models.FloatField()),
                ('bangla_marks', models.FloatField()),
                ('prediction', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.student')),
            ],
        ),
    ]
